### ISSUE TITLE
contract verlängern

### ISSUE THREAD

**Issue by sheepyhollow** [ClockGU/features#1]
Es sollte eine userfreundliche Methode geben, einen bestehenden Vertrag zu verlängern, ohne den Wizard komplett durchlaufen zu müssen.

**Comment by mimischi** [comment]
Die Optionen sind doch zwei:

1) Für jede Vertragsverlängerung (=faktisch ein neuer Vertrag) wird bei Clock ein neuer `Contract` angelegt.
2) Bei einer Vertragsverlängerung ändert ein User einfach nur das Enddatum von `Contract`.

Option 2 wird aktuell nur im Frontend nicht erlaubt, das Backend macht da munter mit. Wenn wir es keine Einwände aus Business-Logik gibt (cc @chgad), dann nehme ich die Restriktion im Frontend einfach raus und wir erlauben die Verlängerung.

**Comment by chgad** [comment]
Das Backend sollte nach jetzigem LOGIKSTAND das eigentlich nur erlauben wenn dadurch Ende - Anfang <= 6 Monate ergibt. Bis jetzt wollten wir einen Vertrag nicht verlängern können...

Wie wäre eine andere Idee:
1. Wir implementieren `Ende - Anfang <= 6 Monate`
2. Wir erlauben ein Update von `end_date` nur im letzten Monat des Vertrags.

Das würde tatsächlich auch das "AZK Übetrags Problem" zur Hälfte lösen. Allerdings möchte ich dem User nicht zu viel Freiheit geben was den `Contract` angeht.

**Comment by mimischi** [comment]
> Allerdings möchte ich dem User nicht zu viel Freiheit geben was den `Contract` angeht.

Weshalb?

**Comment by sheepyhollow** [comment]
Hier müssen wir unbedingt eine Lösung finden.

**Comment by chgad** [comment]
User sollen eienn Vertrag maximal um 6 Monate, gemmesen vom aktuellen `end_date` , verlängern können.

So verhindern wir ein böswilliges "unendlich" verlängern.

**Comment by mimischi** [comment]
Im Frontend können Verträge jetzt maximal um 6 Monate am Stück verlängert werden. Schließe das Issue vorerst.
