### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by sheepyhollow** [ClockGU/features#13]
Einige Fragen zum Verhalten beim Export (aus Slack-Diskussion)

1) wird der exportierte Monat gesperrt?
  a) Wann und wie wird das kommuniziert?
2) wird der vorangegangene Monat gesperrt?
3) wann und wie wird ein Review erzwungen?
4) gibt es ggf. eine Unterscheidung zwischen einem vorläufigen und einem endgültigen Export?

**Comment by mimischi** [comment]
Mittlerweile werden die Reports exportiert, ohne das die Schichten im Monat gelockt werden, oder? Dann kann das Issue nämlich geschlossen werden.

**Comment by sheepyhollow** [comment]
Ich glaube, das ist nicht mehr aktuell.
