### ISSUE TITLE
Notifications/Messaging

### ISSUE THREAD

**Issue by sheepyhollow** [ClockGU/features#15]
Die User sollen innerhalb der App über Vorgänge informiert werden
- nichtkritische Fehler
- Konflikte / kritische Punkte bei angelegten Schichten 
- Updates
- ggf. generelle Hinweise oder Nachrichten

Da muss es wohl auch was im Backend zu geben, oder docken wir uns an einen externen Dienst an?

**Comment by mimischi** [comment]
Ich habe das Issue auch noch mal verschoben, da wir hier zu erst einen Scope definieren müssen:

- Gibt es eine globale Ansicht für Mitteilungen?
- Wo kommen die Mitteilungen her? Bei einigen macht es Sinn diese nur im Frontend (z.B. Absturzmeldungen) oder Backend (z.B. Updates) zu generieren. Aber was ist nun z.B. mit Konflikten die es zu lösen gibt, oder wenn eine Schicht übermäßig lang ist.
- Wie halten wir uns auf dem Laufenden, dass ein User eine Nachricht schon gelesen hat? Der Lesestatus von Update-Benachrichtigungen sollten also geräteübergreifend im Backend gespeichert werden.

**Comment by sheepyhollow** [comment]
Ist das ein Feature für die Open Beta?
Falls ja, Milestone vergeben und als konkrete Aufgabe im jeweiligen Repo anlegen.

**Comment by sheepyhollow** [comment]
Mit den noch zu erwartenden Updates rückt das für mich irgendwie wieder in den Vordergrund. Ich finde es schade, dass wir unsere User nicht gescheit informieren können. 

Darum mein Vorschlag:

- Wir übernehmen das message-model von SOLID, ggf. ohne das Image-Feld.
- wir zeigen die Message(s) im Dashboard an.

Das sollte (?) relativ einfach gehen und löst das Problem, dass wir bislang keinen definierten Kanal von uns zu den Usern haben. Ein aufgemotzteres Tool (siehe Diskussion oben) wäre sicher schick, ist aber im Moment nicht so wichtig und kann auch später noch drangeflanscht werden.

Meinungen dazu, @chgad @mimischi ?

**Comment by mimischi** [comment]
Finde ich sinnvoll! Wenn wir "nur" den Code von SOLID kopieren müssen, dann ist das Ganze im Backend ja schnell implementiert?

**Comment by mimischi** [comment]
Gelöst in https://github.com/ClockGU/clock-frontend/commit/2d72c6735315c96de90480322ac706b6ca59ff3b.
