### ISSUE TITLE
Hilfe Seite

### ISSUE THREAD

**Issue by mimischi** [ClockGU/features#19]
Wir sollten eine Hilfe-Seite einrichten: ein großes Fragezeichen oben rechts in der Titelleiste oder per FAB unten rechts?

Auf der Hilfe-Seite sollte noch mal stehen, dass manchmal ein neu laden der Seite helfen kann.

**Comment by sheepyhollow** [comment]
Fürs erste könnte aber eine Kurzreferenz genügen. 

Mittelfristig sollt die Hilfeseite aber das Handbuch (aktuell in der Gitbook Doku) ersetzen und ggf. noch weitere Informationen haben. Es sollte aber auch strukturierbar sein, d.h. mehrere untereinander verlinkbare Seiten haben.

Fragen, die sich mir dabei stellen:
* Wie editiert man diese Seiten? (Code -> neuer build; Admin-interface -> eigenes model; ...)
* Wie werden sie ausgeliefert? (eigener View, Overlay...)

**Comment by mimischi** [comment]
Ich würde eine simple FAQ Seite vorstellen, in der ein paar Fragen abgefrühstück werden. Für den Rest verweist man auf das Handbuch!

**Comment by sheepyhollow** [comment]
FAQ existiert längst!
