### ISSUE TITLE
contract onboarding

### ISSUE THREAD

**Issue by sheepyhollow** [ClockGU/features#2]
Beim Anlegen eines neuen Vertrags muss es eine Möglichkeit geben, einen von 0 (ausgeglichen) abweichenden Stand des AZK einzugeben.

**Comment by sheepyhollow** [comment]
> bei anschließendem Vertrag kann das Guthaben mitgenommen werden, bei Unterbrechungen sollte zuvor ein Freizeitausgleich erfolgen. (Hr. Scharf)

**Comment by sheepyhollow** [comment]
Das ist auch bis zum Release zu lösen; siehe auch das verwandte Issue #1 
Wir brauchen die passende Logik und einen Onboarding-Prozess nach dem 1st Login.

**Comment by chgad** [comment]
> bei anschließendem Vertrag kann das Guthaben mitgenommen werden, bei Unterbrechungen sollte zuvor ein Freizeitausgleich erfolgen. (Hr. Scharf)

Mit diesem Zitat sollte das mitnehmen von Stunden nicht gesondert behandlet werden.

Ich denke an etwas wie folgendes:

- Erstellen eines `Contract`s ist nur möglich wenn `end` -`start`<= 6 Monate ist.
- Ein verlängern eines `Contract`s ist ab dem letzten Vertragsmonat möglich  `end` - `now` <= 1 Monat
- Eine Verlängerung ist um maximal 6 Monate möglich.

Somit muss kein Übertrag an irgendeiner Stelle eingetragen werden, da der Vertrag weiter gültig ist und somit
auch weiter `Report` objekte erstellt werden.

**Comment by mimischi** [comment]
Zitat von Christian: 
> Ich denke an etwas wie folgendes: [...]

Heißt das also, dass ein User zuerst einen Vertrag mit einer Länge von maximal 6 Monaten erstellt. Im 5. Monat kann der User diesen nun um einen weiteren Monat verlängern. Das kann der User im jeweils letzten Monat solange machen, bis die gesamte Vertragslaufzeit 12 Monate ist?

Wenn das so ist, dann ist das aus UX-Sicht unnötig aufwändig. Ich verlängere meinen Vertrag mit der Uni ja in einem Durchgang und nicht jeden Monat neu?

Zitat von Bertram, weiter oben: 
> 2. User steigt während der Vertragslaufzeit auf Clock um

Das ist ja doch eigentlich das wichtigste hier. Wir müssen Usern erlauben mitten im Vertrag einzusteigen. Aktuelles Beispiel wäre, wenn ein User jetzt einen Vertrag seit April 2020 hat, welcher bis Oktober 2020 geht. Im Juli beginnt dieser User Clock zu nutzen und hat vorher die Excel Variante genutzt.

Am einfachsten wäre es hier, wenn der User sein AZK Guthaben (die Werte des Vormonats) bei der Erstellung des Vertrags eintragen kann. Ich sehe hier technisch auch nicht das Problem, dass von dem "normalen Flow" zu lösen. Es entstehen ja zwei Fälle:

1) Der Vertrag wird für z.B. 6 Monate erstellt und von Anfang an genutzt (Monat 1). Clock erstellt also ab Monat 1 jeweils 6 Report Objekte. Das ist die aktuelle Funktionalität.
2) Der Vertrag wird für z.B. 6 Monate erstellt, aber erst ab irgendeinem Monat genutzt (z.B. Monat 3). Der User trägt also das Report Objekt für Monat 2 nach, um das mitgenommene Guthaben zu definieren. Clock erstellt nun ab Monat 3 selbstständig Report Objekte, insgesamt 4 an der Zahl. Am Vertragsende existieren also 5 Report Objekte.

Beim Erstellen des neuen Report Objekts braucht Clock ja nur a) die Schichten des jeweiligen Monats und b) die Daten aus dem vorherigen Report Objekt. Die Schichten zu dem vorherigen Report Objekt müssen nicht existieren.

**Comment by chgad** [comment]
> Vertrag mit einer Länge von maximal 6 Monaten erstellt. Im 5. Monat kann der User diesen nun um einen weiteren Monat verlängern. Das kann der User im jeweils letzten Monat solange machen, bis die gesamte Vertragslaufzeit 12 Monate ist?

Nein... Wenn du einmal Verlängerst ist die Zeitperiode um die du verlängern darfst maximal 6 Monate. Am Ende dieser Verlängerten Zeit, darf man wieder um maximal 6 Monate verlängern.

**Comment by mimischi** [comment]
Ok! Das heißt verlängern ist hier von der Logik equivalänt zum Erstellen eines neuen Vertrags. Nur das eben einzig der alte Vertrag aktualisiert wird.

Bleibt noch die Frage bzgl. Import des AZK Guthabens! :)

**Comment by sheepyhollow** [comment]
Stimme zu, dass das keinen explizit designten Flow braucht.
Eine Verlängerung ist ein (ggf. explizites) Neuanlegen mit den den gleichen Parametern außer Datum - aber eben einem Startwert/Übertrag, die auch automatisch ausgefüllt werden sollten.

**Comment by mimischi** [comment]
Wir reden doch von zwei Optionen, oder?

1) User verlängert durchwegs den gleichen Vertrag
2) User erstellt jedes mal einen neuen Vertrag.

Wir wissen allerdings nicht ob User das eine oder das andere bevorzugen. Für beide Fälle brauchen wir den Mechanismus des AZK Übertrages. Für 1) benötigen wir dazu noch einige extra Restriktionen die nur zur Verlängerung gelten.

Wäre es nicht sinnvoller erstmal bei 2) zu bleiben, da hier nur der AZK Übertrag fehlt? Die Übernahme der Daten des vorherigen Vertrags kann ja im Frontend stattfindet.

**Comment by mimischi** [comment]
Wir müssen an unserer Dokumentation arbeiten. Dieser Kommentar lässt drauf schließen das wir uns schon mal geeinigt haben keine Verlängerung zu zulassen: https://github.com/ClockGU/features/issues/11#issuecomment-578752161

**Comment by chgad** [comment]
Also auf ein Feld, das den aktuellen Stand des AZK zum Zeitpunkt des erstellen dess Vertrages beinhaltet, kommen wir nicht drum herum. Jetzt ist mir allerding klar wie ich das programmatisch umsetze. Nennen wir dieses Feld einfach mal `azk_stand` und es habe das Format eines datetime-objektes.

Was muss nun beachtet werden:

1. Um keine fälschlichen negativ Arbeitszeiten aufgrund nicht eingetragener Schichten in den Vormonaten zu erzeugen dürfen wir
    keine Report-Objekte erstellen für den Zeitraum `start_date` bis `now` sondern nur für den Monat der Erstellung.
   Es muss also das Signal zu Erstellung ([hier](https://github.com/ClockGU/clock-backend/blob/develop/api/utilities.py#L43)) so 
   verändert werden, dass [hier](https://github.com/ClockGU/clock-backend/blob/develop/api/utilities.py#L65) anstelle
   von `timedelta(0)` nun `contract.azk_stand` steht. 

==> Wir haben erstmal einen Report.

2. Es bleibt das Problem, dass der dieser "Offset" ja bei einem Update verschwinden würde. Dazu müssen wir [hier](https://github.com/ClockGU/clock-backend/blob/develop/api/utilities.py#L107) im Update Signal schlicht weg als 
    `carry_over_hours = contract.azk_stand` setzen.


Ja es klingt jetzt so simpel aber war etwas aus dem Flow... (ein gaaaaaanz klein wenig)

P.S.: Etwas Eigenlob: Durch die gute Struktur und den Flow ist so ein Feature einfach zu implementieren.

**Comment by mimischi** [comment]
Das klingt doch super! Um es Zusammenzufassen: wir fragen bei der Vertragserstellung einen optionalen Wert ab, der im ersten Report-Objekt in einem extra Feld hinterlegt wird. Dieses Feld wird dann für die Rechungen genutzt.

Ein paar Fragen bleiben sind aber noch offen:
- Wie übermitteln wir denn diesen Wert bei der Vertragserstellung? Kommt der mit in den `POST /contracts/` Request?
- Müssen wir diesen Wert mit einem Datum versehen? Für wann ist dieser AZK-Wert gültig: für den aktuellen Monat, oder eventuell für den letzten oder den davor?

**Comment by chgad** [comment]
> Wie übermitteln wir denn diesen Wert bei der Vertragserstellung?

Jap, der wird einfach mit abgespeichert.

> Müssen wir diesen Wert mit einem Datum versehen? 

Ja, das habe ich mir so gedacht, dass dieser Wert für den Monat, in dem der Vertrag erstellt wird, benutzt wird.
Somit ist der erste Report nicht im monat von `start_date` sonder im `now.date`.

**Comment by mimischi** [comment]
> Ja, das habe ich mir so gedacht, dass dieser Wert für den Monat, in dem der Vertrag erstellt wird, benutzt wird.
Somit ist der erste Report nicht im monat von `start_date` sonder im `now.date`.

Gibt es ein Problem wenn wir den User das Datum definieren lassen? Dann könnte der erste Report nicht nur in `now.date` sein, sondern in `some.date`. Falls der Wert des importierten AZK-Kontos aus irgendeinem Grund aus einem Monat ist, der nicht `now.date` ist.

In diesem Fall muss `some.date >= start_date and some.date <= now.date` sein.

**Comment by chgad** [comment]
Nein, es spricht nichts dagegen nur würde ich den Usecase nicht sehen.
Fall 1)
Du wechwelst zu Clock zu Beginn des Monats.
==> Du musst ein paar Schichten (ca. 2 pro Tag) nachtragen

Fall 2) 
Du wechselst gegen Ende des Monats.
==> mach den Monat noch mit Excel fertig und starte am 1. des nächsten mit der Vertragserstellung.

**Comment by mimischi** [comment]
Fall 3) Ich erfahre von Clock und schließe den 1. Monat mit Excel ab, nutze aber Clock nicht sofort. Da ich im Hinterkopf habe, dass es Clock gibt will ich Excel nicht weiter nutzen. Deswegen vermerke ich meine Schichten im 2. Monat nicht. Im dritten Monat überwinde ich mich endlich und melde mich bei Clock an. Nun will ich das AZK aus dem 1. Monat eingeben und selbständig die Schichten aus dem 2. Monat nachtragen. Dadurch starte ich im 3. Monat mit Clock durch.

—

Ich gebe dir recht, es ist ein Edge case und die ersten beiden Fälle sind wichtiger. Allerdings ist es doch gut wenn wir ohne Aufwand auch den 3. Fall abbilden können, wenn uns dieser absolut nicht ins Bein schießt. Dadurch würde im Frontend neben dem AZK Guthaben auch ein Datum (Monat/Jahr) abgefragt.

**Comment by mimischi** [comment]
Eine Frage: soll die Eingabe der AZK Daten nur bei Vertragserstellung gehen? Oder auch beim aktualisieren eines soeben erstellen Vertrags, wenn noch keine Schichten existieren? Das würde nämlich eher Probleme schaffen?

cc @sheepyhollow

**Comment by sheepyhollow** [comment]
Haben wir das eigentlich nun konzeptionell gelöst? @chgad @mimischi 
Oder steht die Frage noch im Raum?

**Comment by sheepyhollow** [comment]
Ich glaube, das ist sogar inhaltlich gelöst und implementiert.
Schließen? @chgad @mimischi

**Comment by mimischi** [comment]
Ja ist erledigt!
