### ISSUE TITLE
Subdomains für clock

### ISSUE THREAD

**Issue by sheepyhollow** [ClockGU/features#20]
Folgende Subdomains werden für `clock.uni-frankfurt.de` bestellt:

`staging.clock.uni-frankfurt.de` (frontend staging)
`preview.uni-frankfurt.de` (frontend `develop` mit production Backend)

`backend.clock.uni-frankfurt.de` (backend)
`staging.backend.clock.uni-frankfurt.de` (backend staging)

**Comment by mimischi** [comment]
@chgad Einigen wir uns auf diese Domainnamen? Oder wollten wir das nun doch anders haben mit dem Backend?

**Comment by chgad** [comment]
> backend.staging.clock.uni-frankfurt.de (backend staging)

Nein! Es sollte `staging.backend.clock.uni-frankfurt.de` heißen. Analog zu `staging.clock.uni-frankfurt.de`.

**Comment by sheepyhollow** [comment]
DNS-Änderung ist beantragt.
