### ISSUE TITLE
Account zurücksetzen

### ISSUE THREAD

**Issue by sheepyhollow** [ClockGU/features#21]
Wir brauchen zur DSGVO-Konformität die Möglichkeit, einen Account (= alle Daten) zu löschen (Recht auf Vergessenwerden). Die bisherigen Überlegungen haben sich mit OAuth2 vielleicht geringfügig geändert, aber nicht viel.

Da ich kein Issue hierzu gefunden habe - hier ist eins.
@chgad @mimischi

**Comment by mimischi** [comment]
Wir hatten uns bisher geeinigt den Account nur als gelöscht zu markieren. Allerdings weiß ich nicht was passiert, wenn User sich danach direkt neu mit CAS einloggen. Wahrscheinlich wirft das Backend dann einen Fehler zurück, weil der Account ja schon existiert. Wir wollen die User aber eigentlich neu einlogge lassen. 

Wollen wir die User ihre Accounts vollständig löschen lassen? Also ohne diese inaktiv zusetzen. Dadurch funktioniert der OAuth Flow bei Neuanmeldungen auch direkt wieder.

Die User verlieren halt alle ihre Daten!

**Comment by sheepyhollow** [comment]
Sollense doch. Wenn es genügend Warnhinweise gibt, dann passt das, finde ich. Das ist doch genau, was das Recht auf Vergessenwerden impliziert - vollständige Löschung aller Daten.

(Oder als letzten Akt noch einen verschlüsselten Dump an den Mailaccount schicken, mit dem man seinen Account wiederherstellen kann? 😁 )

**Comment by mimischi** [comment]
Ist im Frontend implementiert (https://github.com/ClockGU/clock-frontend/commit/64be3cccbd0318a882d5ce012ec8a91c07c00332) und im Backend ist der PR (https://github.com/ClockGU/clock-backend/pull/125) offen.

**Comment by sheepyhollow** [comment]
Ich glaube, das ist erledigt.
