### ISSUE TITLE
Shift Shifts

### ISSUE THREAD

**Issue by sheepyhollow** [ClockGU/features#24]
Kann man die Endzeit im `Shift Form` mit verschieben, wenn man die Startzeit ändert, so dass die Gesamtdauer der Shift bleibt?
Kalender machen das oft so, dass die Termindauer konstant bleibt.

Ist die Frage, ob das für Shifts auch ein typisches Szenario ist. Beim `Resolve` würde es einem aber entgegenkommen - und Drag&Drop (falls irgendwann aktiviert) würde ja das gleiche implizieren.

**Comment by mimischi** [comment]
Finde ich gut! Fiel mir gerade auch als Problem auf.

Wir machen das aber nur a) bei der Startzeit und b) wenn die Startzeit hinter die Endzeit rückt.

**Comment by sheepyhollow** [comment]
Ist das ausreichend diskutiert für ein Frontend-Issue?

**Comment by sheepyhollow** [comment]
Ich bin unsicher, ob ich Fall b) richtig verstehe.
D.h. wenn ich die Startzeit um eine halbe Stunde vorverlege, dann bleibt die Endzeit?

**Comment by mimischi** [comment]
> D.h. wenn ich die Startzeit um eine halbe Stunde vorverlege, dann bleibt die Endzeit?

Ja, oder? Sonst kommen User in das Problem, dass sie die Endzeit richtig setzen, die Startzeit kurz anpassen und dann erneut die Endzeit korrigieren müssen.
