### ISSUE TITLE
Stundenzettel per Mail schicken

### ISSUE THREAD

**Issue by sheepyhollow** [ClockGU/features#6]
An Stelle eines PDF-Downloads kann man den Stundenzettel direkt per Mail irgendwohin schicken.

Nur, weil wir das irgendwann mal diskutiert hatten...

**Comment by sheepyhollow** [comment]
Könnte grundsätzlich ein Datenschutzproblem sein.

**Comment by mimischi** [comment]
> Könnte grundsätzlich ein Datenschutzproblem sein.

Weshalb?

**Comment by sheepyhollow** [comment]
Weil man dann die Mailadresse einer dritten Person eingeben (und ggf. speichern) muss, deren Zustimmung man nicht hat oder erst einholen müsste.

**Comment by mimischi** [comment]
Ahso, daran habe ich gerade gar nicht mehr dran gedacht. Ich ging gerade einfach nur von einem Mailversand an den User aus.

**Comment by sheepyhollow** [comment]
Aahhh ... Ja, das wäre eine Option.
Das andere (an Vorgesetzte) ist außerdem von anderen Randbedingungen abhängig. Die Stundenzettel müssen ja unterschrieben sein, das geht schonmal nicht (so lange praktisch niemand mit digitalen Unterschriften umgehen kann). Man könnte mit dem Sekretariat absprechen, dass man die online einreicht und jedes Semester einmal alle unterschreibt etc. Aber das sind individuelle Absprachen, für die wir keinen Workflow vorsehen müssen.

Aber Mail an eigene Adresse als Alternative könnte man machen!

**Comment by sheepyhollow** [comment]
(...und der nächste Schritt ist dann ein "Warenkorb", so dass man alle auf einmal in einer Mail bekommt... #4 :grin:)

**Comment by sheepyhollow** [comment]
Das Thema wurde interessanterweise auch mit dem DSB diskutiert.
Eine Möglichkeit könnte sogar sein, dass die ganzen Stundenzettel  - irgendwann mal - digital in einem _vault_ gespeichert werden können und die Dienststelle nur eine Art Quittung erhält. Der Dokumentationspflicht für den Zoll wäre Genüge getan und keiner würde Kram abheften und Meterweise Ordner anlegen.

**Comment by sheepyhollow** [comment]
Essentially a duplicate of #27
